### ISSUE TITLE
Improving the github workflows

### ISSUE THREAD

**Issue by lsglab** [lsglab/frontend#11]
The following changes will be involved in the process:
- `.github/no-response.yml` > Fix the required label
- `.github/auto_assign.yml` > Flip AddAssignees to false
- `.github/semantic.yml` > Change titleAndCommits to commitsOnly, flip the other two options
- `.github/delete-merged-branch-config.yml` > Configuring the delete-merged-branch app

**Comment by GitGangGuy** [comment]
In addition, this might also involve having the automatic project assigner intelligently assign different labels (feature, bug) to different projects via if statements.
In the future, I would like to take a look at https://github.com/marketplace/actions/github-wiki-action
