### ISSUE TITLE
Articles

### ISSUE THREAD

**Issue by Flosi23** [lsglab/frontend#23]
**New Feature: Article pages**

I would like to write a ``[slug].svelte`` inside an ``article`` folder that fetches data from our cms and then builds the article page depending on the received data.

If my proposed data structure for the article component (see attached files) will be approved and kept, I see no problem in writing the file, even though our cms doesn't exists yet.

**The structure is supposed to work like this:**
![grafik](https://user-images.githubusercontent.com/56218180/89432626-a2a83480-d741-11ea-9847-b206ffc8c13f.png)

- each article component must have an title, image and slug (the slug is used to identify the correct component to fetch) and one   article section component
- One can add as many articleSection as liked, each of them requires to have a title and content

**Comment by Flosi23** [comment]
I forgot to mention this earlier but I would highly recommend to replace the markdown rich text editor by a WYSIWYG editor.
How this is done (it worked when I dit it on my local machine) is shown here: https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi

**Comment by lsglab** [comment]
@all-contributors add @Flosi23 for code, content, design and ideas

**Comment by GitGangGuy** [comment]
@all-contributors add @Flosi23 for code, content, design and ideas
