### ISSUE TITLE
Prettier throws error when running: yarn do:autofix

### ISSUE THREAD

**Issue by Flosi23** [lsglab/frontend#59]
**Describe the bug**
When running do:autofix the following error message shows up 
![grafik](https://user-images.githubusercontent.com/56218180/94295326-5cad6700-ff61-11ea-8a69-a2cf2543b14c.png)

OS: Windows 10

**Comment by GitGangGuy** [comment]
I can't reproduce this. I have no related global packages installed and even after a fresh clone & install I'm not encountering this problem. Could you provide more detail and look into your local configuration? Are you sure you have installed all dependencies after switching branches?

**Comment by Flosi23** [comment]
### Issue fixed

Ok. I managed to fix the error. The problem were these single quotes:
`'./**/*.{html,css,pcss,scss,svelte}\'`
It seems like windows has a problem with them, so you have to replace them with double quotes and escape them:
`\"./**/*.{html,css,pcss,scss,svelte}\"`

**Comment by Flosi23** [comment]
I am going to commit and push these changes so the error won't occure in the future.

**Comment by Lacrimus** [comment]
In the default cmd, single quotes are not used to escape characters or strings.
Reference:
https://stackoverflow.com/questions/24173825/what-does-single-quoting-do-in-windows-batch-files
