### ISSUE TITLE
stylelint error: unknown pseudo-class selector ":global"

### ISSUE THREAD

**Issue by Lacrimus** [lsglab/frontend#62]
At /src/components/common/Text.svelte

:global(element) selectors within the parent div {} element are not recognized. I understand this is a rewrite of the code below.

Debug:
  8:3  ×  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
 13:3  ×  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
 17:3  ×  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
 24:3  ×  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
 28:3  ×  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
 32:3  ×  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
 36:3  ×  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
 ...............

Does this miss the "&" (Parent) - Selector before the pseudo class?

**Comment by GitGangGuy** [comment]
Could you clarify what branch you're working on?

**Comment by Lacrimus** [comment]
The branch is issue-57-Implement_old_layout
It has failed the "CI / Test and Deploy (push)" check

> 
> 
> Could you clarify what branch you're working on?

**Comment by GitGangGuy** [comment]
> It has failed the "CI / Test and Deploy (push)" check

Are you talking about a specific PR here? I wasn't able to find it, apparently there aren't any other open PRs except my own atm. Could you open one and reference it?

> The branch is issue-57-Implement_old_layout

I'm not sure about the specifics of issue 57 as I'm not developing it, and the Text component isn't included in my issue-53 branch (which issue-57 branched off of). I will assign @Flosi23 to take a look at this.

> At /src/components/common/Text.svelte

I glanced at the file myself and your intuition

> Does this miss the "&" (Parent) - Selector before the pseudo class?

is partially right - it depends on the desired outcome. If the `:global` selector should be applied to the element itself, an `&` is missing. If all children should be targeted with the `:global` selector, a `*` is missing.  Besides, we should restrain from using global selectors in components anyways. Always try to use tailwind first, and only if an implementation using its built-in classes or by extending the `tailwind.config.js` doesn't make sense revert to "traditional" scss in components. In my opinion, global css should only be applied from scss files, and not from within components. This prevents confusion around where global styles originated from and bad coding habits. I also noticed that the component would override important properties like font-family, which I would also highly recommend against. We might want to arrange a jitsi meeting together and talk through this.

**Comment by Flosi23** [comment]
The text component is a component i wrote about a month ago and thus doesnt work correctly, yet.
For now you can comment it out.
I will fix these errors tomorrow.
@GitGangGuy in this case the global selector is used to style html thats inside a slot (autogenerated html from the cms) and as far as I know this is the only way to do so.

**Comment by GitGangGuy** [comment]
@Flosi23,
> as far as I know this is the only way to do so

While it is impossible to target elements not existent in the raw svelte html, you might want to work around this by not using a `slot` and instead inserting the cms data into a designated `div` (or whatever) and styling that. Slots provide a way for developers to add children to a component, and shouldn't be used for automatically inserted content.

**Comment by GitGangGuy** [comment]
There are two problems being raised here: A stylelint error due to an unrecognized pseudo-class (from svelte-preprocess) which doesn't exist in vanilla css, and the mess in the `/src/components/common/Text.svelte` component.
From now on, this issue will be about the stylelint error only. The discussion about the Text component can be moved to a separate issue if necessary.

**Comment by GitGangGuy** [comment]
The [stylelint docs](https://stylelint.io/user-guide/rules/selector-pseudo-class-no-unknown) regarding the `selector-pseudo-class-no-unknown` rule highlight how to [ignore pseudo-classes](https://stylelint.io/user-guide/rules/selector-pseudo-class-no-unknown#optional-secondary-options). I will be pushing the change to my branch (#53), others can merge it in.

**Comment by GitGangGuy** [comment]
Fixed with #53
