### ISSUE TITLE
Nav.svelte component questions / ideas for design improvements

### ISSUE THREAD

**Issue by Lacrimus** [lsglab/frontend#63]
- [ ] Question: Is letter stacking inteded here?

![Unbenannt1](https://user-images.githubusercontent.com/55695243/96377192-25a72b80-1184-11eb-9301-085b337d86fd.PNG)

- [ ] Suggestion: In moble / tablet mode, could the menu cards be fixed to the scroll position? (unless the screen height requires a second scrollbar due to content overflow)

![Unbenannt2](https://user-images.githubusercontent.com/55695243/96377447-11642e00-1186-11eb-98d2-0ba357c1150d.PNG)
Scrolled up
![Unbenannt3](https://user-images.githubusercontent.com/55695243/96377449-12955b00-1186-11eb-8fe3-fdb40bed807f.PNG)
Scrolled further down

- [ ] Lastly, how about sppeding up the fade-in/-out, slide-down/-up animations? The nav element slightly laggs behind cursor movement. See the transition from Nav.svelte at line 482:
![Unbenannt4](https://user-images.githubusercontent.com/55695243/96377723-cba86500-1187-11eb-893b-c3efdba10b4f.PNG)

**Comment by Flosi23** [comment]
The nav is obsolote. I think @GitGangGuy is currently writing a new one with tailwind. Anyway, letter spacing is not intended ans it is a good idea to fix it to the scroll position. But as sad, it wont make scence to Apple these changes now as the file is obsolete.

**Comment by GitGangGuy** [comment]
Removed with #53
