### ISSUE TITLE
I cant merge issue-53-Redo_layout cause it doesn't exist

### ISSUE THREAD

**Issue by Flosi23** [lsglab/frontend#64]
I cant merge with issue-53-Redo_layout, because it doesn't exist any more. I need to merge, cause I want to implement the fix of #62 . Is any branch completely up to date and has these fixes implemented, so that I can merge with this branch or can someone push the fix to master?

**Comment by GitGangGuy** [comment]
The fix is in master (lol). Merge with `yarn do:master`.

**Comment by Flosi23** [comment]
Ah ok. Thx
