### ISSUE TITLE
demo-for-presentation

### ISSUE THREAD

**Issue by Lacrimus** [lsglab/frontend#74]
Please merge all currently developed features into this issue-branch until Friday 30.10.2020 for presentation.

**Comment by GitGangGuy** [comment]
Master is the demo branch. We can tag it when it's ready to be presented.

**Comment by Lacrimus** [comment]
This was not the intention. I presume most of our WIP features to be incomplete at the time, which is why I would have liked to have them implemented in this branch. As far as my point of view for the repository goes, master is only for compleate features (your script asks for breaking changes after all).

**Comment by Lacrimus** [comment]
Furthermore, commits to master are not feasable as you stated yourself.

**Comment by GitGangGuy** [comment]
@Lacrimus I'm strongly opposed to the idea of having a separate branch in addition to master containing identical commits. Anything that can be merged into your suggested branch could just as easily be merged into master, and I would argue against presenting incomplete features that can't be merged into master in a demo branch. This breaks trunk based development in so many ways and causes a lot of weird/unrelated merges and confusion. 

Master is effectively the current release. If something isn't release-able, it doesn't get into master. If a feature needs more than a couple days, it should be split (I have not followed through on this one as much as I should've). There's no need for a second trunk, and no need to present buggy/not finalized features.
The landing page looks pretty done to me. I'll be wrapping things up in master and go over the code once more, but I'm sure @Flosi23 has done a good job and I might only do minor refactoring. From what I understand, the point of our demo on Friday is to give a rough idea of how the proposed website design would look like, not to deliver anything more than what we currently have.
I'll be closing this once again. If you feel the urge to re-open the issue, nothing will stop you.

**Comment by GitGangGuy** [comment]
@all-contributors add @Lacrimus for ideas and code
